spring:
  application:
    name: data-generator

  main:
    web-application-type: none

  profiles:
    default: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        delivery.timeout.ms: 10000
        enable.idempotence: true

app:
  generator:
    topic: ${KAFKA_TRANSACTIONS_TOPIC}
    batch:
      min-size: 5
      max-size: 20
      min-interval-ms: 2000
      max-interval-ms: 5000
    amount:
      min: 100.00
      max: 5000.00
    coordinate-spread-meters: 50
    max-occurred-at-delay-seconds: 10

logging:
  level:
    root: WARN
    ru.tbank.tmap: INFO
    org.springframework: WARN
